-- Natus POS — seed optionnel
--
-- Utilisateurs : npm run seed:users
-- (Marrakech & Casablanca — mot de passe Natus2026!)
--
-- Les commandes Shopify de démo ne sont plus chargées automatiquement.
-- Pour vider la base : npm run reset:orders
